/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef, useEffect, useState } from "react";
import { useGLTF, Clone, Html } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import pokeballImageUrl from "../src/assets/pokeball.png";
import pokemonJson from "../src/data/pokemons.json";

export default function Machine(props) {

    const [pokemons, setPokemons] = useState([]);
    const [imagePath, setImagePath] = useState(pokeballImageUrl);
    useEffect(() => {
        let randomPokemons = [];

        for (let i = 0; i < 9; i++) {
            let randomPokemon = pokemonJson[Math.floor(Math.random() * pokemonJson.length)];
            randomPokemons.push(randomPokemon);
        }
    
        setPokemons(randomPokemons);
    }, []);

    const { nodes, materials } = useGLTF("/vending-machine.glb");
    const pokeball = useGLTF("/pokeball.glb");

    /* Exterior material */
    materials.mat5.metalness = 0.3
    materials.mat5.roughness = 0.5
    materials.mat5.color = new THREE.Color(0xee1515)

    /* Buttons material */
    materials.mat23.metalness = 0.3
    materials.mat23.roughness = 0.5
    materials.mat23.color = new THREE.Color(0x222224)

    /* Buttons hovered material */
    const buttonHoveredMaterial = materials.mat23.clone()
    buttonHoveredMaterial.color = new THREE.Color(0x444446)

    /* Pokeballs refs */
    const pokeball1 = useRef()
    const pokeball2 = useRef()
    const pokeball3 = useRef()
    const pokeball4 = useRef()
    const pokeball5 = useRef()
    const pokeball6 = useRef()
    const pokeball7 = useRef()
    const pokeball8 = useRef()
    const pokeball9 = useRef()
    const pokemonName = useRef()

    // Stats refs
    const attackStat = useRef()
    const specialAttackStat = useRef()
    const defenseStat = useRef()
    const specialDefenseStat = useRef()

    const hoverButtonEvent = (event) => {
        event.object.material = buttonHoveredMaterial
        document.body.style.cursor = "pointer"

    }

    const unhoverButtonEvent = (event) => {
        event.object.material = materials.mat23
        document.body.style.cursor = "default"
    }

    const clickButtonEvent = (event) => {
        let id = event.object.name.split("-")[1]

        pokemonName.current.children[0].innerHTML = pokemons[id - 1].name.charAt(0).toUpperCase() + pokemons[id - 1].name.slice(1);

        attackStat.current.innerHTML = pokemons[id - 1].attack.toString().padStart(3, '0');
        specialAttackStat.current.innerHTML = pokemons[id - 1].special_attack.toString().padStart(3, '0');
        defenseStat.current.innerHTML = pokemons[id - 1].defense.toString().padStart(3, '0');
        specialDefenseStat.current.innerHTML = pokemons[id - 1].special_defense.toString().padStart(3, '0');

        setImagePath(pokemons[id - 1].image)
    }

    const clickUpButtonEvent = (event) => {
        event.object.position.z = 0
    }

    const clickDownButtonEvent = (event) => {
        event.object.position.z = 0.005
    }

    useFrame((state, delta) => {
        for (let i = 1; i <= 9; i++) {
            let pokeball = eval(`pokeball${i}`)
            pokeball.current.rotation.y += 0.5 * delta
        }
    })

    return (
        <group {...props} dispose={null}>
            <group>
                <group name="backPanel">
                    <mesh
                        name="mesh1858506000"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh1858506000.geometry}
                        material={materials.mat5}
                    />
                    <mesh
                        name="mesh1858506000_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh1858506000_1.geometry}
                        material={materials.mat23}
                    />
                </group>
                <group name="rightBlock">
                    <mesh
                        name="mesh1887676826"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh1887676826.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="mesh1887676826_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh1887676826_1.geometry}
                        material={materials.mat5}
                    />
                    {/* Screen */}
                    <mesh
                        name="group850966255"
                        castShadow
                        receiveShadow
                        geometry={nodes.group850966255.geometry}
                        material={materials.mat23}
                        scale={[1.2, 1.8, 0.1]}
                        position={[-0.073, -0.26, -0.026]}
                    >
                        <Html
                            transform
                            occlude
                            scale={[0.01, 0.01, 0.01]}
                            rotation-y={Math.PI}
                            // Attach position to the parent mesh
                            position={[-0.005, 0.165, -0.008]}
                        >
                            <div style={{
                                color: "white",
                                marginTop: "-10px",
                                marginLeft: "-10px",
                                display: "flex",
                                gap: "20px",
                            }}>
                                <div>
                                    <p style={{ marginTop: '5px', marginBottom: '5px' }}>Att.</p>
                                    <p style={{ marginTop: '5px', marginBottom: '5px' }}>A. Sp.</p>
                                    <p style={{ marginTop: '5px', marginBottom: '5px' }}>Def.</p>
                                    <p style={{ marginTop: '5px', marginBottom: '5px' }}>D Spe.</p>
                                </div>
                                <div>
                                    <p ref={attackStat} style={{ marginTop: '5px', marginBottom: '5px' }}>___</p>
                                    <p ref={specialAttackStat} style={{ marginTop: '5px', marginBottom: '5px' }}>___</p>
                                    <p ref={defenseStat} style={{ marginTop: '5px', marginBottom: '5px' }}>___</p>
                                    <p ref={specialDefenseStat} style={{ marginTop: '5px', marginBottom: '5px' }}>___</p>
                                </div>
                            </div>
                        </Html>
                    </mesh>
                </group>
                <group name="leftBlock">
                    <mesh
                        name="mesh19616759"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh19616759.geometry}
                        material={materials.mat5}
                    />
                    <mesh
                        name="mesh19616759_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh19616759_1.geometry}
                        material={materials.mat23}
                    />
                </group>
                <group name="topBlock">
                    <mesh
                        name="mesh1222169380"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh1222169380.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="mesh1222169380_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh1222169380_1.geometry}
                        material={materials.mat5}
                    />
                </group>
                <group name="lowerSeparator">
                    <mesh
                        name="mesh522768280"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh522768280.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="mesh522768280_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh522768280_1.geometry}
                        material={materials.mat5}
                    />
                </group>
                <group name="bottomBlock">
                    <mesh
                        name="mesh1653716828"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh1653716828.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="mesh1653716828_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh1653716828_1.geometry}
                        material={materials.mat5}
                    />
                </group>
                <mesh
                    name="topShelf"
                    castShadow
                    receiveShadow
                    geometry={nodes.group1394142260.geometry}
                    material={materials.mat5}
                    scale={[1, 1, 0.8]}
                />
                <group
                    name="middleShelf"
                    scale={[1, 1, 0.8]}
                >
                    <mesh
                        name="mesh351965626"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh351965626.geometry}
                        material={materials.mat5}
                    />
                    <mesh
                        name="mesh351965626_1"
                        castShadow
                        receiveShadow
                        geometry={nodes.mesh351965626_1.geometry}
                        material={materials.mat23}
                    />
                </group>
                <group name="pokeballs">
                    <Clone
                        ref={pokeball1}
                        name="pokeball-1"
                        object={pokeball.scene}
                        position={[0.065, 0.087, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                    <Clone
                        ref={pokeball2}
                        name="pokeball-2"
                        object={pokeball.scene}
                        position={[0.025, 0.087, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                    <Clone
                        ref={pokeball3}
                        name="pokeball-3"
                        object={pokeball.scene}
                        position={[-0.015, 0.087, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                    <Clone
                        ref={pokeball4}
                        name="pokeball-4"
                        object={pokeball.scene}
                        position={[0.065, 0.027, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                    <Clone
                        ref={pokeball5}
                        name="pokeball-5"
                        object={pokeball.scene}
                        position={[0.025, 0.027, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                    <Clone
                        ref={pokeball6}
                        name="pokeball-6"
                        object={pokeball.scene}
                        position={[-0.015, 0.027, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                    <Clone
                        ref={pokeball7}
                        name="pokeball-7"
                        object={pokeball.scene}
                        position={[0.065, -0.033, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                    <Clone
                        ref={pokeball8}
                        name="pokeball-8"
                        object={pokeball.scene}
                        position={[0.025, -0.033, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                    <Clone
                        ref={pokeball9}
                        name="pokeball-9"
                        object={pokeball.scene}
                        position={[-0.015, -0.033, 0.015]}
                        scale={0.06}
                        rotation={[0, Math.PI / 4, 0]}
                    />
                </group>
                <mesh
                    name="mainGlass"
                    castShadow
                    receiveShadow
                    geometry={nodes.group1016280600.geometry}
                    material={materials.mat24}
                    scale={0.99}
                />
                <group name="topContainer">
                    <mesh
                        name=""
                        castShadow
                        receiveShadow
                        geometry={nodes.group577397298.geometry}
                        material={materials.mat5}
                    />
                    <mesh
                        name="group330894576"
                        castShadow
                        receiveShadow
                        geometry={nodes.group330894576.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="group1894010372"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1894010372.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="group850966255"
                        castShadow
                        receiveShadow
                        geometry={nodes.group850966255.geometry}
                        material={materials.mat23}
                        scale={[6, 1, 1]}
                        position-x={0.02}
                    >
                        <Html
                            ref={pokemonName}
                            transform
                            occlude
                            scale={[0.01, 0.05, 0.01]}
                            rotation={[0, Math.PI, 0]}
                            position={[-0.005, 0.165, -0.008]}
                        >
                            <h1 style={{
                                color: "white",
                                textAlign: "center",
                                fontSize: "18px",
                                fontFamily: "Arial",
                            }}>
                                Pick one
                            </h1>
                        </Html>
                    </mesh>
                </group>
                <group name="foot">
                    <mesh
                        name="group1471477505"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1471477505.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="group1871551305"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1871551305.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="group2031757081"
                        castShadow
                        receiveShadow
                        geometry={nodes.group2031757081.geometry}
                        material={materials.mat23}
                    />
                    <mesh
                        name="group1982615210"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1982615210.geometry}
                        material={materials.mat23}
                    />
                </group>
                <mesh
                    name="rightWhiteBlock"
                    castShadow
                    receiveShadow
                    geometry={nodes.group134552523.geometry}
                    material={materials.mat24}
                >
                    <Html
                        transform
                        scale={0.015}
                        rotation-y={Math.PI}
                        position={[-0.08, 0.095, -0.028]}
                    >
                        <img src={imagePath} />
                    </Html>
                </mesh>
                <group name="buttons">
                    <mesh
                        name="button-1"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1266518904.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                    <mesh
                        name="button-2"
                        castShadow
                        receiveShadow
                        geometry={nodes.group735136140.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                    <mesh
                        name="button-3"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1071800688.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                    <mesh
                        name="button-4"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1762590557.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                    <mesh
                        name="button-5"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1934226556.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                    <mesh
                        name="button-6"
                        castShadow
                        receiveShadow
                        geometry={nodes.group1740258887.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                    <mesh
                        name="button-7"
                        castShadow
                        receiveShadow
                        geometry={nodes.group447741993.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                    <mesh
                        name="button-8"
                        castShadow
                        receiveShadow
                        geometry={nodes.group302109995.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                    <mesh
                        name="button-9"
                        castShadow
                        receiveShadow
                        geometry={nodes.group361576900.geometry}
                        material={materials.mat23}
                        onClick={clickButtonEvent}
                        onPointerUp={clickUpButtonEvent}
                        onPointerDown={clickDownButtonEvent}
                        onPointerEnter={hoverButtonEvent}
                        onPointerLeave={unhoverButtonEvent}
                    />
                </group>
            </group>
        </group>
    );
}

useGLTF.preload("/vending-machine.glb");
